spring:
  application:
    name: solveranet-backend
  
  # Importamos el archivo .env que está en la carpeta (en la raíz del monorepo)
  config:
    import: optional:file:../.env[.properties]

  # Configuración de conexión a PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5434/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Configuración de Hibernate (El ORM)
  jpa:
    hibernate:
      # NUNCA usamos 'update' en producción. Flyway es el dueño de la BD.
      ddl-auto: validate
    show-sql: true # Útil para ver las consultas en la consola mientras desarrollas
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuración de Flyway (Versionado de BD)
  flyway:
    enabled: true
    baseline-on-migrate: true

# Puerto donde correrá el backend de Spring Boot
server:
  port: 8080

app:
  cors:
    allowed-origins: http://localhost:4200